const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
(async()=>{
 const root=path.resolve(__dirname,'../..'),data=JSON.parse(fs.readFileSync(path.join(root,'ai-skill-ui/demo-data.json')));
 const b=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await b.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.UI_URL||'http://127.0.0.1:8922/ai-skill-ui/');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Demo 준비 완료'));
 const results=[];
 async function test(id,name,fn){try{await fn();results.push({id,name,status:'PASS'});}catch(e){results.push({id,name,status:'FAIL',error:e.message});}}
 async function ask(mode){await page.click(`[data-example=${mode}]`);await page.click('#submit');await page.locator('#results').waitFor({state:'visible'});}
 function noSyntax(text){assert(!/^\s*#{1,6}\s|\*\*|^\s*-\s/m.test(text),text.slice(0,200));}
 await test('READ01','접힌/펼친 결과 Markdown 기호 없음',async()=>{for(const s of data.scenarios){await ask(s.mode);noSyntax(await page.locator('#results').innerText());await page.locator('#results details').evaluateAll(ds=>ds.forEach(d=>d.open=true));noSyntax(await page.locator('#results').innerText());assert.equal(await page.locator('#results .rendered-source h4').count()>0,true);}});
 await test('READ02','Control별 독립 카드·그룹',async()=>{await ask('document');assert.equal(await page.locator('.control-card').count(),9);assert.equal(await page.locator('.control-card').evaluateAll(cs=>new Set(cs.map(c=>c.id)).size),9);assert.equal(await page.locator('.grouped-controls').count(),4);for(const group of await page.locator('.grouped-controls').all())assert.equal(await group.locator('.control-section').count(),9);});
 await test('READ03','전체 상세 기본 접힘',async()=>{for(const s of data.scenarios){await ask(s.mode);assert.equal(await page.locator('#results details[open]').count(),0);assert(await page.locator('#results details').count()>0);}});
 await test('READ04','상세 열기·닫기·내용 가시성',async()=>{await ask('guide');const d=page.locator('.activity-details').first();assert.equal(await d.locator('summary').textContent(),'상세 내용 보기 ▼');await d.locator('summary').click();await page.waitForFunction(()=>document.querySelector('.activity-details summary').textContent.includes('닫기'));assert(await d.locator('.excerpt').isVisible());await d.locator('summary').click();await page.waitForFunction(()=>document.querySelector('.activity-details summary').textContent.includes('보기'));assert(!(await d.locator('.excerpt').isVisible()));});
 await test('READ05','원문 핵심 활동·실제 수치',async()=>{for(const s of data.scenarios){await ask(s.mode);let activity=0,evidence=0;for(let i=0;i<s.controls.length;i++){const c=s.controls[i],titles=[...c.fields['Implementation Guide'].matchAll(/^####\s+(.+)$/gm)].map(m=>m[1]);activity+=titles.length;evidence+=[...c.fields['Evidence'].matchAll(/^\s*-\s+\*\*([^*]+)\*\*:?/gm)].length;const shown=await page.locator('.key-activities').nth(i).locator('li').allTextContents();assert.deepEqual(shown,titles.slice(0,3).map(t=>t.replace(/^\d+\.\s*/,'')));}const stats=await page.locator('.result-stats').innerText();assert(stats.includes(`실행 활동 ${activity}개`));assert(stats.includes(`Evidence ${evidence}개`));}});
 await test('READ06','실제 Evidence chip·설명',async()=>{for(const s of data.scenarios){await ask(s.mode);for(let i=0;i<s.controls.length;i++){const expected=[...s.controls[i].fields['Evidence'].matchAll(/^\s*-\s+\*\*([^*]+)\*\*:?/gm)].slice(0,3).map(m=>m[1].replace(/:$/,''));assert.deepEqual(await page.locator('.evidence-chips').nth(i).locator('span').allTextContents(),expected);}assert((await page.locator('#results').innerText()).includes('실행했다는 것을 확인할 수 있는 자료'));}});
 await test('READ07','근거 확장·Source 렌더링·원문 보존',async()=>{const sourcePage=await b.newPage();for(const s of data.scenarios){await ask(s.mode);for(let i=0;i<s.controls.length;i++){const card=page.locator('.control-card').nth(i);await card.locator('.source-details summary').click();const a=card.locator('a.source');assert(await a.isVisible());assert((await a.innerText()).includes(s.controls[i].source));await sourcePage.goto(new URL(await a.getAttribute('href'),page.url()).href);await sourcePage.locator('#source-content h4').first().waitFor();noSyntax(await sourcePage.locator('body').innerText());assert((await sourcePage.locator('#source-text').textContent()).includes(s.controls[i].fields['Control Statement']));assert(!(await sourcePage.locator('#source-text').isVisible()));}}await sourcePage.close();});
 await test('READ08','Quick navigation 해당 카드 이동',async()=>{await ask('document');const links=page.locator('.control-nav a');assert.equal(await links.count(),9);await links.last().click();assert(new URL(page.url()).hash==='#control-sup-c-08');const box=await page.locator('#control-sup-c-08').boundingBox();assert(box.y>=0&&box.y<1080);});
 await test('READ09','3개 Demo·안전 태그·adapter 유지',async()=>{const baseline=JSON.parse(fs.readFileSync(process.env.UX_BASELINE));for(const f of ['ai-skill-ui/demo-data.json','ai-skill-ui/runtime-adapter.js'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'),baseline[f]);for(const s of data.scenarios){await ask(s.mode);assert.equal(await page.locator('.control-card').count(),s.controls.length);for(const tag of ['가이드라인 근거','AI 제안','확인 필요','조직 결정 필요'])assert((await page.locator('#results .tag').allTextContents()).includes(tag));}});
 await test('READ10','다른 기능에서 예시 자동 선택·입력',async()=>{for(const s of data.scenarios){await page.click(`[data-mode=${s.mode==='guide'?'plan':'guide'}]`);await page.click(`[data-example=${s.mode}]`);assert.equal(await page.locator(`[data-mode=${s.mode}]`).getAttribute('aria-pressed'),'true');assert.equal(await page.inputValue('#question'),s.question);await page.click('#submit');assert(!(await page.locator('#error').isVisible()));}});
 await test('READ11','기존 UX12개 실제 실행 결과',async()=>{const r=JSON.parse(fs.readFileSync(path.join(__dirname,'ux-test-results.json')));assert.equal(r.total,12);assert.equal(r.pass,12);assert.equal(r.fail,0);});
 await test('READ12','기존 UI10개 실제 실행 결과',async()=>{const r=JSON.parse(fs.readFileSync(path.join(__dirname,'ui-test-results.json')));assert.equal(r.total,10);assert.equal(r.pass,10);assert.equal(r.fail,0);});
 await test('READ13','UI 외 파일 변경/삭제/추가 0',async()=>{const baseline=JSON.parse(fs.readFileSync(process.env.UX_BASELINE));const files=execFileSync('rg',['--files','--hidden','-g','!.git'],{cwd:root,encoding:'utf8'}).trim().split('\n');for(const f of files.filter(f=>!f.startsWith('ai-skill-ui/'))){assert(f in baseline);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'),baseline[f],f);}for(const f of Object.keys(baseline).filter(f=>!f.startsWith('ai-skill-ui/')))assert(fs.existsSync(path.join(root,f)));});
 await ask('document');await page.locator('#results').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'readability-desktop.png')});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'readability-mobile.png'),fullPage:true});
 await b.close();assert.equal(errors.length,0);const pass=results.filter(r=>r.status==='PASS').length;const out={total:13,pass,fail:13-pass,passRate:pass/13*100,browserErrors:errors,scope:'local only; UI/UX suites executed before READ11/12',results};fs.writeFileSync(path.join(__dirname,'readability-test-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));process.exitCode=out.fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
