const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
(async()=>{
 const root=path.resolve(__dirname,'../..');
 const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
 const catalog=read('ai-skill-ui/data/controls.json'),metadata=read('ai-skill-ui/data/showcase.json'),demo=read('ai-skill-ui/demo-data.json');
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const results=[];async function test(id,name,fn){try{await fn();results.push({id,name,status:'PASS'});}catch(e){results.push({id,name,status:'FAIL',error:e.message});}}
 async function ask(mode){await page.click(`[data-example=${mode}]`);await page.click('#submit');await page.locator('#results').waitFor({state:'visible'});}
 async function overview(){if(await page.locator('#overview-toggle').getAttribute('aria-expanded')!=='true')await page.click('#overview-toggle');}
 async function reset(){await page.click('#explorer-reset');}
 function noMarkdown(text){assert(!/^\s*#{1,6}\s|\*\*|^\s*-\s/m.test(text),text.slice(0,200));}
 await page.goto(process.env.UI_URL||'http://127.0.0.1:8933/ai-skill-ui/');
 await page.waitForFunction(()=>document.querySelector('#showcase-status').textContent.includes('Showcase 자료 준비 완료'));
 await test('SHOW01','AI Skill 소개와 6개 navigation',async()=>{assert((await page.locator('#skill-definition').innerText()).includes('실무 문서 초안 작성을 지원하는 AI Skill'));assert.deepEqual(await page.locator('.showcase-nav a').allTextContents(),['AI Skill','직접 사용하기','Control 탐색','동작 원리','검증 결과','GapZer0 연결']);assert.equal(await page.locator('#overview-toggle').getAttribute('aria-expanded'),'false');});
 await test('SHOW02','Problem/Solution 요약 펼치기',async()=>{await overview();assert(await page.locator('.problem-solution').isVisible());for(const t of ['Problem','Solution','찾기 어렵습니다','실제 원문'])assert((await page.locator('.problem-solution').innerText()).includes(t));});
 await test('SHOW03','3개 기능에서 직접 사용하기 이동',async()=>{assert.equal(await page.locator('.feature-overview>section').count(),3);for(const mode of ['guide','plan','document']){await overview();await page.click(`[data-start-demo=${mode}]`);assert.equal(await page.locator(`[data-mode=${mode}]`).getAttribute('aria-pressed'),'true');assert.equal(await page.inputValue('#question'),demo.scenarios.find(s=>s.mode===mode).question);}assert.equal(await page.locator('#overview-toggle').getAttribute('aria-expanded'),'false');});
 await test('SHOW04','Demo 3개와 오류 없는 결과',async()=>{for(const s of demo.scenarios){await ask(s.mode);assert.equal(await page.locator('.control-card').count(),s.controls.length);assert(!(await page.locator('#error').isVisible()));}});
 await test('SHOW05','다른 기능에서 예시 자동 선택',async()=>{for(const s of demo.scenarios){await page.click(`[data-mode=${s.mode==='guide'?'plan':'guide'}]`);await ask(s.mode);assert.equal(await page.locator(`[data-mode=${s.mode}]`).getAttribute('aria-pressed'),'true');assert.equal(await page.inputValue('#question'),s.question);}});
 await test('SHOW06','결과 요약·실제 Control 수',async()=>{for(const s of demo.scenarios){await ask(s.mode);assert((await page.locator('#result-summary').innerText()).includes(`Control ${s.controls.length}개`));assert.equal(await page.locator('.control-nav a').count(),s.controls.length);}});
 await test('SHOW07','Control 원문 접기·펼치기',async()=>{await page.fill('#explorer-search','CON-C-01');await page.click('[data-control-id="CON-C-01"]');const detail=page.locator('.explorer-original');assert(!(await detail.locator('.rendered-source').isVisible()));await detail.locator('summary').click();assert(await detail.locator('.rendered-source').isVisible());await detail.locator('summary').click();assert(!(await detail.locator('.rendered-source').isVisible()));});
 await test('SHOW08','Markdown DOM 렌더링',async()=>{await ask('plan');await page.locator('#results details').evaluateAll(ds=>ds.forEach(d=>d.open=true));noMarkdown(await page.locator('#results').innerText());await page.locator('.explorer-original summary').click();noMarkdown(await page.locator('#explorer-detail').innerText());assert(await page.locator('.explorer-original h4').count()>0);});
 await test('SHOW09','Explorer 121개 단일 source와 pagination',async()=>{await reset();assert.equal(catalog.count,121);assert.equal(new Set(catalog.controls.map(c=>c.id)).size,121);assert.equal(await page.locator('.explorer-card').count(),12);while(await page.locator('#explorer-more').isVisible())await page.click('#explorer-more');assert.equal(await page.locator('.explorer-card').count(),121);});
 await test('SHOW10','Control ID 검색·빈 결과',async()=>{await page.fill('#explorer-search','IAM-C-01');assert.equal(await page.locator('.explorer-card').count(),1);assert.equal(await page.locator('.explorer-card strong').textContent(),'IAM-C-01');await page.fill('#explorer-search','GZ-FAKE-999');assert.equal(await page.locator('.explorer-card').count(),0);assert((await page.locator('#explorer-results').innerText()).includes('검색 결과가 없습니다'));});
 await test('SHOW11','keyword·이름 검색·HTML 입력 안전',async()=>{await reset();await page.fill('#explorer-search','퇴사자');const expected=catalog.controls.filter(c=>(c.id+' '+c.name+' '+c.keywords.join(' ')).includes('퇴사자')).map(c=>c.id);assert(expected.length>0);assert.deepEqual(await page.locator('.explorer-card strong').allTextContents(),expected.slice(0,12));await page.fill('#explorer-search','신뢰할 수 있는 백업');assert((await page.locator('.explorer-card strong').allTextContents()).includes('CON-C-01'));await page.fill('#explorer-search','<img src=x onerror=alert(1)>');assert.equal(await page.locator('#explorer-results img').count(),0);assert.equal(await page.locator('.explorer-card').count(),0);});
 await test('SHOW12','Domain 실제 값 filter',async()=>{await reset();const domains=[...new Set(catalog.controls.map(c=>c.domain))].sort();assert.deepEqual(await page.locator('#explorer-domain option').allTextContents(),['모든 Domain',...domains]);const domain='Identity and Access Management';await page.selectOption('#explorer-domain',domain);const expected=catalog.controls.filter(c=>c.domain===domain);assert.equal(await page.locator('.explorer-card').count(),expected.length);assert((await page.locator('.explorer-card small').allTextContents()).every(t=>t.startsWith(domain)));});
 await test('SHOW13','Class 실제 값·복합 filter',async()=>{assert.deepEqual(await page.locator('#explorer-class option').allTextContents(),['모든 Class',...[...new Set(catalog.controls.map(c=>c.classification))].sort()]);await page.selectOption('#explorer-class','Common');assert.equal(await page.locator('.explorer-card').count(),catalog.controls.filter(c=>c.domain==='Identity and Access Management'&&c.classification==='Common').length);await page.fill('#explorer-search','IAM-C-01');assert.equal(await page.locator('.explorer-card').count(),1);});
 await test('SHOW14','Control 상세 실제 필드·Source',async()=>{await page.click('[data-control-id="IAM-C-01"]');const c=catalog.controls.find(c=>c.id==='IAM-C-01');for(const f of ['Control Objective','Control Statement','Control Owner','Stakeholders','Evidence']){assert(await page.locator(`[data-field="${f}"]`).isVisible());assert(c.fields[f]);}assert((await page.locator('.explorer-source').innerText()).includes(c.source));assert((await page.locator('[data-field="Control Owner"]').innerText()).includes(c.fields['Control Owner']));});
 await test('SHOW15','7단계 Skill Flow',async()=>{assert.equal(await page.locator('.skill-flow li').count(),7);assert.deepEqual(await page.locator('.skill-flow b').allTextContents(),['사용자 요청','요청 유형 판단','필요한 조직 정보 확인','Control Index 검색','실제 Control 원문 확인','적용성 판단','실무 결과 생성']);});
 await test('SHOW16','실제 Skill 구성요소 repository path',async()=>{const d=page.locator('#how-it-works>details').first();await d.locator('summary').click();for(const t of ['SKILL.md','Control Index','Control Sources','Output Formats','Tests','Codex Runtime','Claude Skill'])assert((await d.innerText()).includes(t));for(const a of await d.locator('[data-repo-path]').all())assert(fs.existsSync(path.join(root,await a.getAttribute('data-repo-path'))));});
 await test('SHOW17','3개 기능 Output 구조·원문 format',async()=>{await overview();const texts=await page.locator('.feature-overview>section').allTextContents();for(const t of ['관련 Control','적용 조건','Source'])assert(texts[0].includes(t));for(const t of ['목표','실행 활동','Owner','Stakeholders','Timing','Evidence','결정사항'])assert(texts[1].includes(t));for(const t of ['목적','적용 범위','역할과 책임','업무 절차','기록/Evidence','검토 및 개선','관련 Control'])assert(texts[2].includes(t));assert.equal(await page.locator('[data-repo-path="skill/references/output-formats.md"]').count(),2);await page.click('#overview-toggle');});
 await test('SHOW18','실제 Grounding 원칙',async()=>{await page.locator('.grounding-section>summary').click();for(const t of ['Source','존재하지 않는 Control ID','숫자','확인 필요','조직 결정 필요','실제 확보 증적','인증 가능 여부'])assert((await page.locator('.grounding-section').innerText()).includes(t));});
 await test('SHOW19','Source traceability 결과→원문',async()=>{await ask('guide');await page.locator('.source-details>summary').first().click();assert((await page.locator('.source-details').first().innerText()).includes('references/controls/05-identity-access-management/common.md#iam-c-01'));const href=await page.locator('a.source').first().getAttribute('href');const r=await page.request.get(new URL(href,page.url()).href);assert.equal(r.status(),200);await page.locator('.traceability-section>summary').click();assert((await page.locator('.traceability-section').innerText()).includes('추천 Control → Control 원문 → Source → 실무 결과'));});
 await test('SHOW20','실제 report 근거 8개 metric',async()=>{assert.equal(await page.locator('.metric-card').count(),8);for(const m of metadata.metrics){assert.equal(await page.locator(`[data-metric=${m.id}] .metric-value`).textContent(),`${m.numerator} / ${m.denominator}`);const source=fs.readFileSync(path.join(root,m.source),'utf8');assert(source.includes(m.reportEvidence));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,m.source))).digest('hex'),m.sourceSha256);}assert((await page.locator('#validation').innerText()).includes('검증 시나리오 범위 기준'));});
 await test('SHOW21','metric마다 검증 내용·범위·PASS 기준·제한·report',async()=>{for(const card of await page.locator('.metric-card').all()){await card.locator('summary').click();for(const t of ['대상:','PASS / 집계 기준:','제한사항:','Report Source'])assert((await card.innerText()).includes(t));await card.locator('summary').click();}});
 await test('SHOW22','Codex/Claude/Web UI 구분',async()=>{assert.deepEqual(await page.locator('.runtime-environments h4').allTextContents(),['Codex','Claude','Web UI']);const text=await page.locator('.runtime-environments').innerText();for(const t of ['실제 Runtime 검증 완료','사용자 제공 실제 실행 요약','실시간 LLM 없음'])assert(text.includes(t));});
 await test('SHOW23','GapZer0 전체 Flow·상세',async()=>{assert.deepEqual(await page.locator('.project-flow>span').allTextContents(),['Framework','Guideline','AI Skill','Virtual Chibbo','Evidence','GRC','Improvement']);const d=page.locator('#gapzero-connection>details').first();await d.locator('summary').click();assert.equal(await d.locator('dt').count(),6);assert((await d.innerText()).includes('자동 실행하는 기능은 없습니다'));});
 await test('SHOW24','E03 실제 report local D·Production 미검증',async()=>{await page.locator('#chibbo-explanation>summary').click();const text=await page.locator('#chibbo-explanation').innerText();for(const t of ['합성 fixture','D — local verification','TVM-C-06','TVM-E-03','TVM-E-04','미검증'])assert(text.includes(t));assert(fs.readFileSync(path.join(root,metadata.sources.e03),'utf8').includes('Production E2E: NOT VERIFIED'));});
 await test('SHOW25','실제 Repository 산출물',async()=>{await page.locator('.artifacts-section>summary').click();assert.equal(await page.locator('#repository-artifacts a').count(),metadata.artifacts.length);for(const p of metadata.artifacts)assert(fs.existsSync(path.join(root,p)));for(const a of await page.locator('#repository-artifacts a').all())assert((await a.getAttribute('href')).startsWith('https://github.com/whs4-GapZer0/GapZer0_Guideline/'));});
 await test('SHOW26','현재 제한과 향후 기능 명확',async()=>{await page.locator('.limitations-section>summary').click();const t=await page.locator('.limitations-section').innerText();for(const v of ['실시간 LLM API를 호출하지 않는','3개만 사용할 수 있습니다','향후 확장 가능성','현재 구현된 기능이 아닙니다','동기화 snapshot'])assert(t.includes(v));});
 await test('SHOW27','Desktop navigation·레이아웃·캡처',async()=>{await reset();await page.locator('.showcase-nav a[href="#control-explorer"]').click();assert(new URL(page.url()).hash==='#control-explorer');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'showcase-explorer-desktop.png')});await page.locator('.showcase-nav a[href="#ai-skill"]').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(__dirname,'showcase-desktop.png')});await page.locator('.showcase-nav a[href="#validation"]').click();await page.screenshot({path:path.join(__dirname,'showcase-validation-desktop.png')});});
 await test('SHOW28','Mobile navigation·Explorer·Demo·캡처',async()=>{await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>document.querySelector('#showcase-status').textContent.includes('준비 완료'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(__dirname,'showcase-mobile.png')});if(await page.locator('.menu-toggle').isVisible())await page.click('.menu-toggle');await page.click('.showcase-nav a[href="#control-explorer"]');await page.fill('#explorer-search','CON-C-01');await page.click('[data-control-id="CON-C-01"]');assert(await page.locator('#explorer-detail').isVisible());await page.screenshot({path:path.join(__dirname,'showcase-explorer-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(await page.locator('.menu-toggle').isVisible())await page.click('.menu-toggle');await page.click('.showcase-nav a[href="#try-demo"]');await ask('plan');assert(await page.locator('#results').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(errors.length,0);});
 await test('SHOW29','기존 실제 UI/UX/READ regression 0',async()=>{for(const [name,count] of [['ui',10],['ux',12],['readability',13]]){const r=read(`ai-skill-ui/tests/${name}-test-results.json`);assert.equal(r.total,count);assert.equal(r.pass,count);assert.equal(r.fail,0);}const baseline=JSON.parse(fs.readFileSync(process.env.UX_BASELINE,'utf8'));for(const p of ['ai-skill-ui/demo-data.json','ai-skill-ui/runtime-adapter.js'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),baseline[p]);});
 await test('SHOW30','ai-skill-ui 외 변경/삭제/추가 0',async()=>{const baseline=JSON.parse(fs.readFileSync(process.env.UX_BASELINE,'utf8'));const files=execFileSync('rg',['--files','--hidden','-g','!.git'],{cwd:root,encoding:'utf8'}).trim().split('\n');for(const p of files.filter(p=>!p.startsWith('ai-skill-ui/'))){assert(p in baseline,p);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),baseline[p],p);}for(const p of Object.keys(baseline).filter(p=>!p.startsWith('ai-skill-ui/')))assert(fs.existsSync(path.join(root,p)),p);});
 await browser.close();const pass=results.filter(r=>r.status==='PASS').length;
 const out={total:30,pass,fail:30-pass,passRate:pass/30*100,browserErrors:errors,scope:'Local Showcase tests; existing UI/UX/READ suites executed separately; no live LLM/deployment',results};fs.writeFileSync(path.join(__dirname,'showcase-test-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));process.exitCode=out.fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
