title: GapZer0 Guideline
longtitle: GapZer0 Security Framework Guideline
author: GapZer0

description: >
  NIST CSF 2.0과 ISMS-P를 기반으로 한
  GapZer0 통합 정보보호 가이드라인

url: "https://whs4-gapzer0.github.io"
baseurl: "/GapZer0_Guideline"

remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
