const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
export const percent=(n,d)=>d>0?`${Number((100*n/d).toFixed(1))}%`:'N/A';
const link=(path,commit)=>{const a=el('a','근거 보기');a.href=path.startsWith('ai-skill-ui/')?'../'+path:`https://github.com/whs4-GapZer0/GapZer0_Guideline/${path.includes('.')?'blob':'tree'}/${commit}/${path}`;a.target='_blank';a.rel='noopener';return a;};
const section=(root,title)=>{const s=el('section',undefined,'quant-section');s.append(el('h3',title));root.append(s);return s;};
const fold=(root,title)=>{const d=el('details',undefined,'quant-detail');d.append(el('summary',title));root.append(d);return d;};
const table=(root,headers,rows)=>{const wrap=el('div',undefined,'quant-table');const t=el('table');const h=el('tr');headers.forEach(x=>h.append(el('th',x)));const head=el('thead');head.append(h);t.append(head);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(v=>{const td=el('td');v instanceof Node?td.append(v):td.textContent=v;tr.append(td);});b.append(tr);});t.append(b);wrap.append(t);root.append(wrap);};
export async function initializeQuantitative(catalog,callbacks){
 const response=await fetch('./data/quantitative.json');if(!response.ok)throw new Error('정량 근거 데이터 로드 실패');const q=await response.json();
 const root=document.querySelector('#quantitative-dashboard');const metrics=new Map(q.metrics.map(m=>[m.id,m]));
 const cards=section(root,'주요 검증 결과');const grid=el('div',undefined,'quant-grid');cards.append(grid);
 q.metrics.forEach(m=>{if(!(m.denominator>0&&m.numerator>=0&&m.numerator<=m.denominator))throw new Error('지표 분모/분자 오류');const c=el('article',undefined,'quant-card');c.dataset.executiveMetric=m.id;c.append(el('h4',m.title),el('strong',`${m.numerator}/${m.denominator} · ${percent(m.numerator,m.denominator)}`),el('p',m.scope),el('small',`${m.measure} · ${m.environment}`),link(m.source,q.sourceCommit));if(['codex','core','regression','claude','agreement'].includes(m.id))c.append(el('small','동기화 전 Runtime 기록 · 이번 외부 Runtime 미실행'));grid.append(c);});
 const donuts=section(root,'대표 검증 범위');const dg=el('div',undefined,'quant-grid');donuts.append(dg);
 ['codex','top5','hit5','claude','showcase'].forEach(id=>{const m=metrics.get(id),box=el('article',undefined,'quant-donut');box.dataset.donut=id;const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 120 120');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${m.title} ${m.numerator}/${m.denominator} ${percent(m.numerator,m.denominator)}`);for(const foreground of [false,true]){const circle=document.createElementNS(ns,'circle');for(const [k,v]of Object.entries({cx:60,cy:60,r:48,fill:'none','stroke-width':9,pathLength:100}))circle.setAttribute(k,v);circle.setAttribute('stroke',foreground?'#71dfb0':'#263c38');if(foreground){circle.setAttribute('stroke-dasharray',`${100*m.numerator/m.denominator} 100`);circle.setAttribute('transform','rotate(-90 60 60)');}svg.append(circle);}const label=document.createElementNS(ns,'text');label.setAttribute('x','60');label.setAttribute('y','65');label.setAttribute('text-anchor','middle');label.textContent=percent(m.numerator,m.denominator);svg.append(label);box.append(svg,el('h4',m.title),el('p',`${m.numerator}/${m.denominator}`),el('small',m.scope));dg.append(box);});
 const bars=section(root,'Top-3 / Top-5 검색 비교');['top3','top5','hit3','hit5'].forEach(id=>{const m=metrics.get(id),r=el('div',undefined,'quant-bar-row');r.dataset.searchMetric=id;r.append(el('span',`${m.title} · ${m.numerator}/${m.denominator} · ${percent(m.numerator,m.denominator)}`));const track=el('div',undefined,'quant-track'),fill=el('div',undefined,'quant-fill');fill.style.width=`${100*m.numerator/m.denominator}%`;track.append(fill);r.append(track);bars.append(r);});bars.append(el('p','Case: 모든 기대 Control이 포함된 질의 / 전체 질의. Hit: 포함된 개별 기대 Control / 전체 기대 Control. 일반 검색 정확도가 아닙니다.'));bars.append(el('p','정량 평가 대상 범위에서는 Top-5까지 확인하면 기대 Control이 모두 검색 범위에 포함됩니다.'));
 const h=section(root,'Top-3에서 놓친 Control은 왜 Top-5에서 잡혔나요?');h.dataset.searchExample='hrs';h.append(el('p',`“${q.searchExample.query}” · 초기 ${q.searchExample.initialRank}위 → ${q.searchExample.rank}위 · ${q.searchExample.score}점`),el('p','Top-3 미포함 / Top-5 포함. 특정 Control ID별 가산점 없이 일반 검색 알고리즘을 개선했습니다.'));const ul=el('ul');q.searchExample.improvements.forEach(v=>ul.append(el('li',v)));h.append(ul,el('small',q.searchExample.implementationScope),link(q.searchExample.source,q.sourceCommit));
 const matrix=fold(root,'검증 지표 상세 — 분모·범위·측정 의미');table(matrix,['검증 영역','환경','테스트 수','PASS / 포함','FAIL / 미포함','성공률','검증 내용','범위','Source'],q.metrics.map(m=>[m.title,m.environment,m.denominator,m.numerator,`${m.denominator-m.numerator} ${m.complementMeaning}`,percent(m.numerator,m.denominator),m.details,`${m.scope} · ${m.limitations}`,link(m.source,q.sourceCommit)]));
 const cases=fold(root,'테스트 케이스 직접 확인 — T01–T10');q.cases.forEach(c=>{const d=fold(cases,`${c.id} · ${c.scenario} · ${c.result}`);d.dataset.testCase=c.id;d.append(el('p',`기대 동작: ${c.expectedBehavior}`),el('p',`검증 포인트: ${c.point}`),link(c.source,q.sourceCommit),link(c.pointSource,q.sourceCommit));});
 const safe=section(root,'안전성 및 근거성 검증');q.safety.forEach(s=>{const p=el('article',undefined,'quant-card');p.dataset.safety=s.id;p.append(el('h4',s.title),el('strong',`${s.observed}/${s.total} · ${s.caseId}`),el('p',s.reportEvidence),link(s.source,q.sourceCommit));safe.append(p);});safe.append(el('p','위 수치는 해당 검증 시나리오에서 관찰한 결과이며, 전체 질의에 대한 발생률을 의미하지 않습니다.'));safe.append(el('p','0/1은 해당 부정 시나리오에서 관찰한 건수입니다. 전체 hallucination rate나 인증 판정 안전성으로 일반화하지 않습니다.'));
 const cross=fold(root,'Codex / Claude 대표 기능 비교');table(cross,['기능','Codex','Claude','Agreement / 측정 의미'],q.runtimeComparison.map(r=>[r.function,`${r.codexId}: ${r.codex}`,`${r.claudeId}: ${r.claude}`,'일치 · 대표 기능 충족 비교 · 동일 입력 paired test / 문장 동일성 아님']));cross.append(el('p',`Representative Functional Agreement ${metrics.get('agreement').numerator}/${metrics.get('agreement').denominator} · 선정된 대표 기능 Scenario 기준`));q.runtimeSources.forEach(p=>cross.append(link(p,q.sourceCommit)));
 const flow=section(root,'Runtime 검증과 Web Demo의 관계');flow.append(el('p',`Control source → Codex ${metrics.get('codex').numerator}/${metrics.get('codex').denominator} / Claude ${metrics.get('claude').numerator}/${metrics.get('claude').denominator} → Web Demo (대표 3개 정적 시나리오)`),el('p','Web Demo는 실시간 LLM 응답이 아닙니다. Runtime 결과와 브라우저 기능 검증은 서로 다른 평가입니다. Codex/Claude Runtime과 T05/T06 결과는 동기화 전의 과거 검증 기록이며 이번에 외부 Runtime을 재실행하지 않았습니다.'));
 const diagram=el('div',undefined,'runtime-diagram');diagram.setAttribute('role','img');diagram.setAttribute('aria-label','GapZer0 Skill Source에서 별도 Codex 13개 Claude 3개 Runtime 검증을 거쳐 정적 Web Showcase Demo로 연결');for(const text of ['GapZer0 Skill Source','↓',`Codex · ${metrics.get('codex').denominator} tests    |    Claude · ${metrics.get('claude').denominator} tests`,'↓','Web Showcase · Demo UI'])diagram.append(el('div',text));flow.append(diagram);
 const method=fold(root,'어떻게 검증했나요?');method.append(el('p','성공률 = 확인된 성공 건수 / 해당 평가 대상 건수 × 100. 화면의 백분율은 JavaScript로 계산하며 소수점 최대 한 자리로 표시합니다.'),el('p','보고서에 기록된 선정 테스트셋만 평가했습니다. 전체 Control 구현률, 전체 보안 업무 정확도, 운영 배포, 실시간 AI 성능 또는 인증 충족을 입증하지 않습니다.'),el('p','Control Dataset은 명시된 원격 main 커밋의 Guideline과 동기화한 시점의 사본입니다. 계속 자동으로 동기화하거나 이후 변경을 반영한다고 보장하지 않습니다. UI 테스트 수치는 해당 테스트셋 범위입니다.'));
 table(method,['방법','실제 측정 범위'],[['Functional Runtime Test','실제 요청 → Control 선택 → 결과 확인'],['Regression Test','T01–T10 기존 기능과 안전 규칙 확인'],['Search Evaluation','8개 질의의 Expected Control Top-k 포함 여부'],['Cross-runtime Test','Codex / Claude 대표 3개 기능 충족 비교; 동일 문장 비교 아님'],['UI Test','로컬 Chromium UI·UX·가독성·Showcase 동작과 회귀 검사']]);const limits=fold(root,'검증 범위와 제한사항');for(const text of ['Web Showcase는 Demo Mode이며 자유질의 Web LLM Runtime은 미연결입니다.','정량 평가는 선정된 테스트셋을 기준으로 합니다. Claude 검증은 대표 시나리오 3개를 기준으로 합니다.','Fake Control 관찰은 T05, 인증 판단 관찰은 T06 단일 Scenario 기준입니다.','최신 Guideline 전체 동기화는 명시된 main 커밋 기준으로 수행했습니다. 실제 외부 Runtime과 운영 배포는 별도 재검증이 필요합니다.','Virtual Chibbo Production S3/API/UI는 이번 검증 범위 밖입니다.'])limits.append(el('p',text));
 const stats=document.querySelector('#dataset-statistics'),all=catalog.controls,total=all.length,domains=[...new Set(all.map(c=>c.domain))],classes=[...new Set(all.map(c=>c.classification))];stats.append(el('h3','Control Dataset — 동기화 시점의 사본'),el('p',`전체 Control ${total}개 · Domain ${domains.length}개`));const count=el('p',`전체 ${total}개 / 현재 필터 ${total}개`);count.id='dataset-filter-count';stats.append(count);document.addEventListener('explorer:results',e=>count.textContent=`전체 ${e.detail.total}개 / 현재 필터 ${e.detail.count}개`);
 const distribution=fold(stats,'Domain / 분류별 분포 — 클릭하여 탐색');for(const [field,values]of [['classification',classes],['domain',domains]]){const block=section(distribution,field==='domain'?'Domain 분포':'Control 분류');values.forEach(value=>{const n=all.filter(c=>c[field]===value).length;const button=el('button',`${value} · ${n}/${total} · ${percent(n,total)}`,'distribution-button');button.type='button';button.dataset.distribution=field;button.dataset.value=value;button.dataset.count=n;button.addEventListener('click',()=>callbacks.filter(field,value));const bar=el('span',undefined,'distribution-fill');bar.style.width=`${100*n/total}%`;button.append(bar);block.append(button);});}stats.append(el('small','분포 백분율의 분모는 동기화 시점의 사본에 포함된 전체 Control 수입니다. 필터 결과와 전체 수를 구분합니다.'));
 const artifacts=document.querySelector('#artifact-map');artifacts.append(el('h3','저장소 산출물 지도'));const tree=el('ul',undefined,'artifact-tree');artifacts.append(tree);q.artifactSources.forEach(path=>{const p=el('li',path+' · ');p.append(link(path,q.sourceCommit));tree.append(p);});
 root.dataset.status='ready';
}
